---
- name: apt-get update
  apt: update_cache=yes upgrade=yes
  
- name: Add apt sources universe and multiverse
  apt_repository: repo="{{item}}" state=present
  with_items:
    - deb http://security.ubuntu.com/ubuntu trusty-security multiverse
    - deb-src http://security.ubuntu.com/ubuntu trusty-security multiverse
    - deb http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty universe
    - deb-src http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty universe
    - deb http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates universe
    - deb-src http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates universe
    - deb http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty multiverse
    - deb-src http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty multiverse
    - deb http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates multiverse
    - deb-src http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates multiverse

- name: reconfigure dash to bash
  file: "dest=/bin/sh src=bash state=link"
  
- name: remove app armor
  apt: name={{item}} state=absent
  with_items:
    - apparmor
    - apparmor-utils  
   
- name: Install packages 
  apt: name={{item}} state=present
  with_items:
    - ssh
#    - openssh-server  open ssh not necessary for cloud images
    - vim-nox
    - ntp 
    - ntpdate
    - python-mysqldb

- name: check if sendmail package installed, store result in sendmail_check variable
  command: dpkg-query -l sendmail
  register: sendmail_check
  changed_when: False
  ignore_errors: yes
  
- name: disable and stop sendmail
  service: name=sendmail state=stopped enabled=no
  when: sendmail_check.stdout.find('no packages found') != -1
  
- name: Install packages 
  apt: name={{item}} state=present
  with_items:
    - postfix 
    - postfix-mysql 
    - postfix-doc 
    - mysql-client 
    - mysql-server 
    - openssl 
    - getmail4 
    - rkhunter 
    - binutils 
    - dovecot-imapd 
    - dovecot-pop3d 
    - dovecot-mysql 
    - dovecot-sieve 
#    - sudo sudo already works on cloud image

- name: Copy postfix config files
  template: src={{item}} dest=/etc/postfix/{{item}} backup=yes
  with_items:
    - main.cf
    - master.cf
   

- name: Start the MySQL service
  action: service name=mysql state=started
  
# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  notify: restart mysql

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: Install packages 
  apt: name={{item}} state=present
  with_items:  
    - amavisd-new
    - spamassassin 
    - clamav 
    - clamav-daemon 
    - zoo 
    - unzip 
    - bzip2
    - arj
    - nomarch
    - lzop
    - cabextract
    - apt-listchanges
    - libnet-ldap-perl
    - libauthen-sasl-perl
    - clamav-docs
    - daemon
    - libio-string-perl
    - libio-socket-ssl-perl
    - libnet-ident-perl
    - zip
    - libnet-dns-perl

- name: stop and remove init scripts of spam assassin
  service: name=spamassassin state=stopped enabled=no

- name: install nginx
  apt: name=nginx state=present

- name: install squirrelmail
  apt: name=nginx state=present
  
- name: stop and remove init scripts of apache2
  service: name=apache2 state=stopped enabled=no
  ignore_errors: yes

- name: start nginx
  service: name=nginx state=started enabled=yes
   
- name: Install packages 
  apt: name={{item}} state=present
  with_items:
  - php5-fpm
  - php5-mysql 
  - php5-curl
  - php5-gd
  - php5-intl
  - php-pear
  - php5-imagick
  - php5-imap
  - php5-mcrypt
  - php5-memcache
  - php5-ming
  - php5-ps
  - php5-pspell
  - php5-recode
  - php5-snmp
  - php5-sqlite
  - php5-tidy
  - php5-xmlrpc
  - php5-xsl
  - php-apc
  
- name: start php5-fpm
  service: name=php5-fpm state=reloaded
  
  